### ISSUE TITLE
Upgrade peer dependency gatsby to support version ^3.0.1

### ISSUE THREAD

**Issue by ernestofgonzalez** [syntra/gatsby-remark-reading-time#11]
Unable to install `gatsby-remark-reading-time` via `npm` due to broken dependency solution.

```shell
egonzalez@egonzalez:~/Documents/hunchat-blog$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: gatsby-starter-blog@0.1.0
npm ERR! Found: gatsby@3.0.3
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"^3.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"^2.0.0" from gatsby-remark-reading-time@1.1.0
npm ERR! node_modules/gatsby-remark-reading-time
npm ERR!   gatsby-remark-reading-time@"^1.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/egonzalez/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/egonzalez/.npm/_logs/2021-03-08T22_50_53_788Z-debug.log
```
Update peer dependency `gatsby` to `^3.0.0`. I will submit a PR to fix this

**Comment by ghost** [comment]
I've opened #13 that allows _both_ Gatsby v2 and Gatsby v3.

**Comment by ernestofgonzalez** [comment]
@alvinometric Awesome! Thanks for the warning

**Comment by ghost** [comment]
No problem! Why did you close your PR?

**Comment by ernestofgonzalez** [comment]
@alvinometric, I have no idea. I actually thought it was one of the maintainers. Must have closed it accidentally.

**Comment by ghost** [comment]
@ErnestoFGonzalez My PR's been merged so we can close this 🙏

**Comment by ernestofgonzalez** [comment]
@alvinometric, Great! Closing this

**Comment by danielimmke** [comment]
This still needs to be published to NPM

**Comment by ghost** [comment]
@danielimmke Feel free to add another comment [here](https://github.com/syntra/gatsby-remark-reading-time/pull/13) for @garetmckinley

**Comment by danielimmke** [comment]
I actually switched to just using gatsby-transformer-remark - it has a timeToRead built in so I don't need an additional plugin.

**Comment by ghost** [comment]
I used the word count too, unfortunately. Even if I could easily write my own...
