### ISSUE TITLE
Does not support the latest version of Gatsby

### ISSUE THREAD

**Issue by good3n** [syntra/gatsby-remark-reading-time#9]
Error on build
`warn Plugin gatsby-remark-reading-time is not compatible with your gatsby version 2.18.4 - It requires gatsby@next`

Gastby version: 2.18.4
Plugin version: Lastest? https://www.gatsbyjs.org/packages/gatsby-remark-reading-time/

**Comment by ariamckinley** [comment]
This has been fixed in the latest release :)
